made a signin popup
Capsonchik/React-NFT pull request #8
Opened 2022-07-03 19:00 UTC by Cra7yy

made a signin popup 
signup form to enter the site

2022-07-03 20:32 UTC, Cra7yy commented
4.1 made a signin popup 
registration form to enter the site added a little animation on the hover added a link to go to the registration page

2022-07-03 20:57 UTC, Capsonchik approved these changes
Принял, жду реализации работы по клику

2022-07-04 07:39 UTC, diana-k22 requested changes
Определиться со стилистикой написания кода)

2022-07-04 07:39 UTC, diana-k22 commented on src/components/Signin/Signin.jsx
> +        <div className="popup__cross"></div>
За что отвечает данный див?

2022-07-04 07:39 UTC, diana-k22 commented on src/components/Signin/Signin.jsx
> +          <input type='password' className='popup__input' minlength="4" maxlength="30" placeholder='password' />
Немного смутило, что где-то ты делаешь двойные кавычки, где-то одинарные. Определись)

2022-07-04 07:48 UTC, Cra7yy commented on src/components/Signin/Signin.jsx
> +        <div className="popup__cross"></div>
popup_cross это крестик закрытия попапа

2022-07-04 07:48 UTC, Cra7yy commented on src/components/Signin/Signin.jsx
> +          <input type='password' className='popup__input' minlength="4" maxlength="30" placeholder='password' />
уже исправлено сегодня с утра будет сегодня до обеда за пушино

2022-07-04 08:06 UTC, Capsonchik approved these changes

2022-07-04 08:07 UTC, merged